# CollectionBuilder
# Jekyll Digital Collection Generator

# URL variables
# site domain
url:
# location on the domain
# e.g. /digital/hjccc
baseurl: /demo/moscon

# url to objects folder
digital-objects: /demo/moscon/objects

# location of code
source-code: https://github.com/CollectionBuilder

# Elasticsearch cluster host
elasticsearch-protocol: http
elasticsearch-host: 0.0.0.0
elasticsearch-port: 9200
elasticsearch-index: moscon_programs_collection

# Site settings
title: Collection Builder CDM Skin
# header and head metadata
tagline: Digital Collection Magic with Static Web Technologies
description: "CollectionBuilder-CONTENTdm is a template for creating digital collection exhibits on top of existing CONTENTdm repositories. This demo features materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s."
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# name of metadata file, be sure to also change page_gen data setting!
metadata: demo_moscon
# page gen settings
# "data" value must be the name of the metadata file
page_gen:
  - data: 'demo_moscon'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'
    filter: 'objectid'

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id:

# Robots exclude
# set noindex to true if you do NOT want Google to index your site
# noindex: true

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
