
# site domain
url: http://0.0.0.0:4000

# url to production objects store
digital-objects: https://collectionbuilder.sfo2.cdn.digitaloceanspaces.com

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
