#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "usage: `basename $0` OBJECTS_DIR OUTPUT_DIR"
    exit 1
fi

# Trim any trailing slash from the paths.
OBJECTS_DIR=${1%/}
OUTPUT_DIR=${2%/}

# Create the output directory if necessary.
if [ ! -d "$OUTPUT_DIR" ]; then
   mkdir $OUTPUT_DIR;
   echo "Created: $OUTPUT_DIR";
fi

for F_PATH in $OBJECTS_DIR/*.pdf; do
    OUT_F_PATH=$OUTPUT_DIR/`basename $F_PATH`.text
    pdftotext -enc UTF-8 -eol unix -nopgbrk $F_PATH $OUT_F_PATH
    echo "Wrote $OUT_F_PATH"
done
